extends Node
enum Dialogue {BUNGOOWANT, BUNGOOTHANKS, BUNGOOFESTIVAL, YAHIEWANT, YAHIETHANKS, YAHIEFESTIVAL, DUNKELWANT1, DUNKELWANT2, DUNKELTHANKS, DUNKELFESTIVAL, WINDMILLSWITCH, TOOPOOR, HATACQUIRED}
enum Voices {YAHIE, DUNKEL, BUNGOO, MEOWGIE, GROEGI}
